### ISSUE TITLE
v2 status and version silkscreen

### ISSUE THREAD

**Issue by fi0** [illness072/elephant42#9]
Is v2 finalized? The silkscreen shows v1.0 in the master branch. Thank you!

**Comment by illness072** [comment]
elephant42 is currently v1.0.  There are no plans for v2.0 yet.

**Comment by fi0** [comment]
Thank you for clarifying. I think I misunderstood v2 case as v2 PCB 😄

**Comment by illness072** [comment]
I'm sorry it's complicated!😂
